spring:
  application:
    name: customer-update-service
  profiles: local
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers: localhost:9092

server:
  port: ${PORT:0} 

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

topic:
  updateUserTopic: "update-customer-service"